### ISSUE TITLE
Error Report

### ISSUE THREAD

**Issue by sammantic** [SelfHealing/Shafi#1]

**Comment by sallamah** [comment]
يا ريت لو قمتم بالانتهاء من 
Task
تضيفوا رابط للوصول لهذا الـ 
Task 
عشان اقدر اشوفه

فمثلا هنا انا محتاج رابط صفحات الـ
HTML 
المتفق عليها

**Comment by sammantic** [comment]
what is accomplished : 
- Html pages are created . and i have already create a task which upload Html pages on GitHub
